### ISSUE TITLE
href reference for Index file...

### ISSUE THREAD

**Issue by pg7001** [rjpcomputing/Remodora#3]
I'm seriously blanking I think on this, but for Step 6 under installation there is an instruction to  change the href attribute <base href=""> in the file index.html to match. 

Match what exactly? Apologies, I am still rather new at coding and I cannot get references at times. Any help with this would be much appreciated. Since I cannot get this to show up in my browser, I'll assume that this href is needed.

Thanks..

**Comment by rjpcomputing** [comment]
@pg7001 I updated the README. Please read step 6 again and see if it makes more sense. If it doesn't I will explain more. Thanks for bringing this to my attention. I think the step was not clear and also I had the formatting wrong in step 7 so you didn't see the optional prefix being used.

Let me know if you need any more help.

**Comment by pg7001** [comment]
I really appreciate the update and information. I'm very close to getting this working and super appreciate the assistance. The good news is that I have the Remodora showing in my browser, the bad is that it seems to be waiting for station info. I'm showing a rather perplexing error in terminal (shown below).  Although it mentions pianobar not running, it actually does show station selections immediately preceding this error message. So, it appears to try and start but then errors. 

I'm guessing this should be an easy correction, however it's eluding me.. 

▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼

./src/pianobar.lua:72: No current song information found. This may be due to pianobar not running
stack traceback:
	/usr/local/share/lua/5.1/turbo/httpserver.lua:251: in function </usr/local/share/lua/5.1/turbo/httpserver.lua:212>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/turbo/iostream.lua:553: in function </usr/local/share/lua/5.1/turbo/iostream.lua:544>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/turbo/ioloop.lua:573: in function </usr/local/share/lua/5.1/turbo/ioloop.lua:572>
▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

**Comment by rjpcomputing** [comment]
@pg7001 So... I think I know what is going on and I am sorry. So I rewrote the entire app a while ago and I removed the login GUI functionality. So now you need to start Remodora once and it will create the config file template. Close Remodora and edit `~/.config/pianobar/config`. Change the file to match your pandora login details
```
user = your@user.name
password = password
```
Let me know if that works. I will make a change to the readme and also an issue so I remember to get the login working again.

**Comment by pg7001** [comment]
Ok, we're making progress. I have a new line in the error message in terminal view, which I believe is relating to the html document. This occurred after I started Remodora once, then went into the config file to update with my pandora login info, then again restarted. 

The webpage appears to draw (shown below), but again is holding on information relay from pianobar ..which appears not to be starting for some reason. 

**[W 2016/08/03 00:53:34] [web.lua] 500 Internal Server Error GET /pianobar/songdetails (10.0.1.4) 7ms
[E 2016/08/03 00:53:34] [web.lua] Error in RequestHandler, thread: 0xb6941798 is dead.**
▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
./src/pianobar.lua:72: No current song information found. **This may be due to pianobar not running**
stack traceback:
	/usr/local/share/lua/5.1/turbo/httpserver.lua:251: in function </usr/local/share/lua/5.1/turbo/httpserver.lua:212>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/turbo/iostream.lua:553: in function </usr/local/share/lua/5.1/turbo/iostream.lua:544>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/turbo/ioloop.lua:573: in function </usr/local/share/lua/5.1/turbo/ioloop.lua:572>
▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

_This is the result as seen from the browser:_

![img_4145](https://cloud.githubusercontent.com/assets/20759160/17350862/2d3a45c4-58f8-11e6-9bfd-24a5d64826cd.PNG)

**Comment by rjpcomputing** [comment]
@pg7001 You are right we are getting close.

Can you run pianobar from your terminal and it actually work.

P.S. Also I have no access to MacOS if you are running Remodora on a Mac it is not tested.

**Comment by pg7001** [comment]
Yes, Pianobar runs from terminal. I logged in, and played music with no problem. 
Unfortunately, it's just getting it communicate with Remodora that's the problem.

**Comment by pg7001** [comment]
when I execute Remodora, I noticed it does call to Pianobar (and loads the config).. however in the end the Turbo handler times out:

**pi@pandora_radio:~/Remodora-master $ ./remodora
[pianobar]	config found and loaded**
[I 2016/08/04 02:29:17] [web.lua] Added src/index.html (4196 bytes) to static file cache. 
[S 2016/08/04 02:29:17] [web.lua] 200 OK GET / (10.0.1.21) 9ms
[I 2016/08/04 02:29:18] [web.lua] Added src/vendor/bootstrap/3.3.4/css/bootstrap.paper.min.css (135263 bytes) to static file cache. 
[I 2016/08/04 02:29:18] [web.lua] Added src/vendor/font-awesome/4.3.0/css/font-awesome.min.css (23739 bytes) to static file cache. 
[I 2016/08/04 02:29:18] [web.lua] Added src/vendor/angular-snap/1.8.1/angular-snap.min.css (1469 bytes) to static file cache. 
[I 2016/08/04 02:29:18] [web.lua] Added src/default.css (2914 bytes) to static file cache. 
[I 2016/08/04 02:29:18] [web.lua] Added src/vendor/angularjs/1.3.15/angular.min.js (125909 bytes) to static file cache. 
[I 2016/08/04 02:29:18] [web.lua] Added src/vendor/angularjs/1.3.15/angular-cookies.min.js (825 bytes) to static file cache. 
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /vendor/font-awesome/4.3.0/css/font-awesome.min.css (10.0.1.21) 58ms
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /vendor/angular-snap/1.8.1/angular-snap.min.css (10.0.1.21) 49ms
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /default.css (10.0.1.21) 49ms
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /vendor/angularjs/1.3.15/angular-cookies.min.js (10.0.1.21) 35ms
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /vendor/angularjs/1.3.15/angular.min.js (10.0.1.21) 77ms
[I 2016/08/04 02:29:18] [web.lua] Added src/vendor/angularjs/1.3.15/angular-resource.min.js (3582 bytes) to static file cache. 
[I 2016/08/04 02:29:18] [web.lua] Added src/vendor/angular-ui/ui-bootstap/0.12.1/ui-bootstrap-tpls-0.12.1.min.js (65187 bytes) to static file cache. 
[I 2016/08/04 02:29:18] [web.lua] Added src/vendor/angular-snap/1.8.1/snap.js (25731 bytes) to static file cache. 
[I 2016/08/04 02:29:18] [web.lua] Added src/vendor/angular-snap/1.8.1/angular-snap.js (9485 bytes) to static file cache. 
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /vendor/bootstrap/3.3.4/css/bootstrap.paper.min.css (10.0.1.21) 191ms
[I 2016/08/04 02:29:18] [web.lua] Added src/common/services.js (1873 bytes) to static file cache. 
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /vendor/angularjs/1.3.15/angular-resource.min.js (10.0.1.21) 64ms
[I 2016/08/04 02:29:18] [web.lua] Added src/app.js (4628 bytes) to static file cache. 
[I 2016/08/04 02:29:18] [web.lua] Added src/common/filters.js (1639 bytes) to static file cache. 
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /vendor/angular-snap/1.8.1/snap.js (10.0.1.21) 56ms
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /vendor/angular-snap/1.8.1/angular-snap.js (10.0.1.21) 51ms
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /app.js (10.0.1.21) 39ms
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /common/services.js (10.0.1.21) 52ms
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /common/filters.js (10.0.1.21) 32ms
[I 2016/08/04 02:29:18] [web.lua] Added src/favicon.ico (38630 bytes) to static file cache. 
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /vendor/angular-ui/ui-bootstap/0.12.1/ui-bootstrap-tpls-0.12.1.min.js (10.0.1.21) 114ms
[S 2016/08/04 02:29:18] [web.lua] 200 OK GET /favicon.ico?v=1 (10.0.1.21) 17ms
**[E 2016/08/04 02:29:18] [web.lua] Error in RequestHandler, thread: 0xb69f0ea8 is dead.**

**Comment by rjpcomputing** [comment]
@pg7001 What are you running Remadora on? OS and CPU? Also how did you install Pianobar? Did you  use a package manager? If so, can you remove Pianobar and try to follow these instructions (https://github.com/rjpcomputing/Remodora/blob/master/doc/notes.md#pianobar)?

Maybe also try running Remodora as root (e.g. $ sudo ./remodora). Remember that this will generate a new config file in `/root/.config/pianobar/config` that you will need to fill in your Pandora credentials.

I am at a loss as to what is the issue. To control Pianobar it uses a FIFO file named `ctl` in the Pianobar config directory. You could verify that gets created.

**Comment by pg7001** [comment]
I tried some other methods to get this working, unfortunately no success. For some reason, Pianobar is not relaying the song information to Remodora. 

To answer your questions, Pianobar and Remodora are installed on a Raspberry Pi, I'm accessing via SSH on a Mac to install all components, and using an iPhone to access the Remodora controls (via Safari). 

I tried running as sudo, unfortunately that will not work either. I have accessed the config file and placed my credentials for Pandora. IF I access Pianobar via the terminal, it will work just fine (music plays, play lists come up, etc.). It's just the Remodora access that is not working...

**Comment by rjpcomputing** [comment]
@pg7001 Sorry for the frustration and thanks for your willingness to debug. Can you give me the directory listing of the config directory using `ls -lah <config_dir>`? Thanks.

**Comment by USAFPride** [comment]
I'm actually experiencing the same issue. oPi running Armbian 5.14. Pianobar plays from the cli. Installed exactly per instructions.  Start remodora and get the below error

pi@orangepipc:~/Remodora$ ./remodora
[pianobar]      config found and loaded
[E 2016/09/13 02:31:06] [web.lua] Error in RequestHandler, thread: 0xb6d88548 is dead.
▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
./src/pianobar.lua:72: No current song information found. This may be due to pianobar not running
stack traceback:
        /usr/local/share/lua/5.1/turbo/httpserver.lua:251: in function </usr/local/share/lua/5.1/turbo/httpserver.lua:212>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/turbo/iostream.lua:553: in function </usr/local/share/lua/5.1/turbo/iostream.lua:544>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/turbo/ioloop.lua:573: in function </usr/local/share/lua/5.1/turbo/ioloop.lua:572>
▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
[W 2016/09/13 02:31:06] [web.lua] 500 Internal Server Error GET /pianobar/songdetails (192.168.1.125) 2ms


load the webpage, and pianobar doesn't start.  Click Pause/Play and shell shows:
Ok.
(i) Get stations... Ok.
|>  Station "xxxxx Radio" (#####################)
(i) Receiving new playlist... Ok.
|>  "Lucky" by "Jason Mraz" on "We Sing, We Dance, We Steal Things"
[E 2016/09/13 02:40:20] [web.lua] Error in RequestHandler, thread: 0xb69a54c8 is dead.
<snip> rest is the same as above

**Comment by USAFPride** [comment]
ok.  I figured it out.  It is not creating the appropriate files in /.config/pianobar/
-rw-r--r-- 1 root root  257 Sep 13 02:27 current_details.json
-rwxr-xr-x 1 root root  602 Sep 13 02:26 events.lua

and at a minimum, these lines are not being added to the config file:
event_command = /.config/pianobar/events.lua
fifo = /.config/pianobar/ctl

Once I created the .json and .lua file and updated the config file, it is playing with no errors. I need to click the play/pause to start it. After that, play/pause does not stop the file, station lists are not loading, and no album art.

When a new song starts, I get:
/!\ Cannot start eventcmd. (No such file or directory)
|>  "Haven't Met You Yet" by "Michael Bublé" on "Crazy Love"
/!\ Cannot start eventcmd. (No such file or directory)

**Comment by rjpcomputing** [comment]
@USAFPride 

This function [[1]](https://github.com/rjpcomputing/Remodora/blob/master/src/pianobar.lua#L79) is what is supposed to take care of a fresh install. Remodora checks to see if this is the first time Remodora has been launched. It is looking for the **config** file (`~/.config/pianobar/config`) to exist. If you ran Pianobar first before running Remodora then Pianobar creates the **config** file and Remodora will not "setup" the directory correctly. Please try to delete the `~/.config/pianobar` directory and run Remodora again.

-----
Just for your information: (please try the above first)
* The **events.lua** file needs to be this file [[2]](https://github.com/rjpcomputing/Remodora/blob/master/src/support/events.lua) and it will generate the _current_details.json_ file. It also need to be given execute permissions (`$ chmod +x events.lua`).
* The FIFO file needs to be created using `$ mkfifo ~/.config/pianobar/ctl`

[1] https://github.com/rjpcomputing/Remodora/blob/master/src/pianobar.lua#L79
[2] https://github.com/rjpcomputing/Remodora/blob/master/src/support/events.lua

**Comment by USAFPride** [comment]
deleted the ~/.config/pianobar directory and ran Remodora again.  Script created pianobar ./config directory as expected. Modified /config with username and password. started ./Remodora
[pianobar] config found and loaded

load webpage, and receive the same "thread: xxxx is dead" error. Stationlists do not load, and pause is showing vs play.  Click Pause and get:

(i) Unrecognized key tls_fingerprint at /home/pi/.config/pianobar/config:12
Welcome to pianobar (2016.06.02-dev)! Press ? for a list of commands.
(i) Control fifo at /home/pi/.config/pianobar/ctl opened
(i) Login... 
Error: Invalid partner credentials.

comment out the rpc_host and tls_fingerprint, restart web page, same as first load (no stationlists and pause showing). Click "Pause" and receive:

Welcome to pianobar (2016.06.02-dev)! Press ? for a list of commands.
(i) Control fifo at /home/pi/.config/pianobar/ctl opened
(i) Login... [S 2016/09/14 00:27:04] [web.lua] 200 OK GET /pianobar/action/pause (192.168.1.125) 230ms
[S 2016/09/14 00:27:04] [web.lua] 200 OK GET /pianobar/songdetails (192.168.1.125) 2ms
Ok.
(i) Get stations... Ok.
         0)  Q  x
         1) q   y
         2)     z
[?] Select station: S
         1) q   x
         2) q   y
[?] Select station: 

Nothing changes in web page.  Reload webpage and stationlists now load, pause button still showing. Click Pause and cycles to play. shell performs a "Get Stations" again. Click "Play" and it works as expected.

Sorry for the long explanation, but I wanted to document each step exactly to help with solving initial setup issues.

**Comment by rjpcomputing** [comment]
@USAFPride,

That is great news!

So some explanation... The play/pause starts as pause with every browser refresh. I have no way to get from pianobar if iti is playing. That feature has been requested and the dev said, "Pianobar is not meant for total remote control. Look elsewhere for complete control." So I do send the pause command and the play command so they are in sync with what is showing on the screen, but that means you need to click the button twice. I am open to ideas and this is not ideal.

I wonder if Pianobar changed the **tls_fingerprint** default and now it works. It didn't always work and it has been working for me for so long I don't change it. I will think about removing it from the default config file.

Now comes an ugly part of Remodora that I have not been able to figure out how to fix. Station selection when there is no previous station saved in the config file... So a tip is that when it gets stuck requesting a station like that I actually press the "Power Off" button. This is because it sends a 'q' to pianobar and it will load the _quickmix_, which all accounts have. Luckily you had a station that started with a 'S' (the keyboard command Pianobar uses for Pause). So I have tried sending the 'q' for you but can't get pianobar to recognize it till it has logged in.

**TIP**: After you select the station for the first time, select "Power Off" in Remodora and then press "Play". This will save the station to the config file and not start in the "Select Station" mode.

**Comment by USAFPride** [comment]
as we have wandered off the original issue (which I think is solved per my findings), I will open other specific issues and attempt to help you fix them.

**Comment by rjpcomputing** [comment]
I was thinking the same thing. Closing and moving to the open issues.
