### ISSUE TITLE
Play/Pause button sync

### ISSUE THREAD

**Issue by USAFPride** [rjpcomputing/Remodora#7]
Upon loading, issue "next song" command as this will automatically start playback. Verify that this works with no station loaded.

**Comment by rjpcomputing** [comment]
@USAFPride,

Are you saying that you verified that sending "next song" works and you verified? Or that we need to verify it works?

**Comment by USAFPride** [comment]
I believe it works. It would need to be tested in your software and verify that it works with no default station (that it will automatically default to "quick mix")
