### ISSUE TITLE
web browser does not show what is currently playing

### ISSUE THREAD

**Issue by rhinomods** [rjpcomputing/Remodora#8]
I had a hard time installing from source since directions were OLD and some of the dependencies were old/could not be found. 
I followed the instructions from  https://cdn-learn.adafruit.com/downloads/pdf/pi-wifi-radio.pdf
Think the dependancys were good except gnutls-dev which I ended up using libcurl4-gnutls-dev
Pianobar installed properly.  connected and got the TLS set.

When I pull the http up  
I see the Big Pandora logo. play pause like dislike buttons. 
But it does not show current track
Does not show Stations.

I am currently writing my OLD pianobar back to another sd card to see if i can get remodora to work on that..  this image i have has been working for 3 years NONstop everyday... I guess i should have installed remodora with that.

**Comment by rhinomods** [comment]
Whoops sorry, maybe pianobar is not loading properly with ./remodora will play more

**Comment by rhinomods** [comment]
ok it will play from station 0 when i press pause, then press again to play. 
it will skip a few songs. but if i press any other button ( or let it play a few songs it will stop playing audio. 
Showing 
` 2017/02/08 14:11:36] [web.lua] 200 OK GET /pianobar/songdetails (10.1.10.185) 3ms                                             
#   -04:55/04:55   `

**Comment by rhinomods** [comment]
Current error 

pi@BR-Pianobar-pi:~ $ sudo systemctl status remodora -l                                                                           
● remodora.service - Control Pandora through a website using pianobar and libpiano.                                               
   Loaded: loaded (/etc/systemd/system/remodora.service; enabled)                                                                 
   Active: active (running) since Wed 2017-02-08 14:48:46 EST; 1min 59s ago                                                       
 Main PID: 334 (luajit)                                                                                                           
   CGroup: /system.slice/remodora.service                                                                                         
           └─334 luajit /var/turbo/remodora/remodora                                                                              

Feb 08 14:49:12 BR-Pianobar-pi remodora[334]: [S 2017/02/08 14:49:07] [web.lua] 200 OK GET //images/song.png (10.1.10.185) 43ms   
Feb 08 14:49:38 BR-Pianobar-pi remodora[334]: [S 2017/02/08 14:49:12] [web.lua] 200 OK GET /pianobar/songdetails (10.1.10.185) 8ms
Feb 08 14:49:38 BR-Pianobar-pi remodora[334]: [S 2017/02/08 14:49:29] [web.lua] 200 OK GET /pianobar/songdetails (10.1.10.185) 4ms
Feb 08 14:49:38 BR-Pianobar-pi remodora[334]: [S 2017/02/08 14:49:34] [web.lua] 200 OK GET /pianobar/songdetails (10.1.10.185) 9ms
Feb 08 14:49:41 BR-Pianobar-pi remodora[334]: [79B blob data]                                                                     
Feb 08 14:49:41 BR-Pianobar-pi remodora[334]: Welcome to pianobar (2016.06.02-dev)! Press ? for a list of commands.               
Feb 08 14:49:41 BR-Pianobar-pi remodora[334]: [60B blob data]                                                                     
Feb 08 14:49:41 BR-Pianobar-pi remodora[334]: [105B blob data]                                                                    
Feb 08 14:49:41 BR-Pianobar-pi remodora[334]: [S 2017/02/08 14:49:41] [web.lua] 200 OK GET /pianobar/songdetails (10.1.10.185) 16m
s                                                                                                                                 
Feb 08 14:49:42 BR-Pianobar-pi remodora[334]: Error: Invalid partner credentials.

**Comment by rjpcomputing** [comment]
It seems like you don't have your Pandora credential saved. Since you are using systemd then the user "www-data" is running Remodora, so you need to edit the config file in `/var/www/.config/pianobar/config`. I am not able to check this location on my raspberry pi right now so it is going from memory, but I think it is close.

**Comment by rhinomods** [comment]
Yeah i got that changed, and it was showing titles after I removed the last two lines from the config that was created. ( TLS and Pandorainfo)
I think it is an issue with my build of pianobar.  
Running just piano bar, it only plays one song then stops.  even if i change stations it does not play the next song. 

sorry for flooding this with multiple issues. 
I am going to try on my old SD card build that was rock steady. ( unfortunately it is raspbian wheezy)

**Comment by rjpcomputing** [comment]
@rhinomods Hey I wrote a simple doc to use to install Pianobar from source. It is not hard. Please read it over and give it a try.

https://github.com/rjpcomputing/Remodora/blob/master/doc/notes.md#pianobar
