### ISSUE TITLE
docker with config directory shared

### ISSUE THREAD

**Issue by petanque** [rjpcomputing/Remodora#9]
Hi, thank you for sharing Remodora, this is my favorite Pianobar remote.
Right now I'm using it in a vm but I want to change to docker.

Is it possible to make a docker image with shared Pianobar config files?
I want to use the audio_pipe in Pianobar and share it with my Snapcast server.

**Comment by rjpcomputing** [comment]
Hi,

I am glad you enjoy Remodora.

I like the idea you have, but I am not sure how to share the config files.
I am sorry I use Docker, but not much of connecting containers together so
I am not exactly sure. Maybe a volume mounted between containers?
--
Regards,
Ryan

**Comment by petanque** [comment]
It works with a volume mount, but the directory is empty so the Pianobar settings is lost and a default file gets created.
I can edit the file and create the audio_pipe fifo in the folder so no problem.

I had a problem with the Dockerfile, when install turbo it fails to download from github so I had to compile from source to make it work. 
I can see that someone else has mentioned a similar problem in 2019 so am not sure if that error is temporary or if a fix is ​​needed.
https://github.com/kernelsauce/turbo/issues/340
